-- Criando a tabela
CREATE TABLE Z_DISASTER_RECOVERY (
    ID NUMBER PRIMARY KEY,
    NOME VARCHAR2(50),
    IDADE NUMBER,
    DATA_INSERCAO TIMESTAMP
);

-- Criando a sequence para gerar IDs
CREATE SEQUENCE Z_DISASTER_RECOVERY_SEQ START WITH 1 INCREMENT BY 1;